task:
  name: ShellCheck
  container:
    image: fedora:latest
    cpu: 1
    memory: 1G
  install_script: dnf install -y ShellCheck
  lint_script: bash testdata/shellcheck.bash

task:
  name: "Starting TASKS: $TASK_NUMBER $CI_DISTRO"
  matrix:
    - container:
        image: debian:latest
        cpu: 1
        memory: 1G
      package_install_script:
        - apt-get update
        - apt-get install -y golang-go
        - apt-get install -y git
      env:
        CI_DISTRO: debian
      matrix:
        - env:
            TASK_NUMBER: Task_One
        - env:
            TASK_NUMBER: Task_Two
  test_script:
    - testdata/starting_tasks.bash
